"""WAF Detection — multi-layer fingerprinting engine."""
from __future__ import annotations
import asyncio
import re
from typing import Any
from talisman.utils.http_client import TalismanHTTPClient
from talisman.utils.logger import get_logger, console

log = get_logger(__name__)

WAF_HEADER_SIGNATURES: dict[str, list[tuple[str, str | None]]] = {
    "Cloudflare":      [("server", "cloudflare"), ("cf-ray", None), ("cf-cache-status", None)],
    "Akamai":          [("server", "AkamaiGHost"), ("x-akamai-transformed", None), ("x-check-cacheable", None)],
    "AWS WAF":         [("x-amz-cf-id", None), ("x-amzn-requestid", None)],
    "Imperva":         [("x-iinfo", None), ("x-cdn", "Imperva")],
    "F5 BIG-IP":       [("server", "BigIP"), ("x-cnection", None)],
    "Sucuri":          [("x-sucuri-id", None), ("server", "Sucuri")],
    "Barracuda":       [("x-barracuda-start-time", None)],
    "FortiWeb":        [("x-iid", None)],
    "Azure Front Door":[("x-azure-ref", None), ("x-fd-healthprobe", None)],
    "StackPath":       [("x-sp-gateway", None)],
    "Varnish":         [("x-varnish", None), ("via", "varnish")],
}

WAF_COOKIE_SIGNATURES: dict[str, list[str]] = {
    "Cloudflare": ["__cflb", "__cf_bm", "__cfruid"],
    "Imperva":    ["incap_ses_", "visid_incap_"],
    "F5 BIG-IP":  ["BIGipServer", "F5_fullWT"],
    "Barracuda":  ["barra_counter_session"],
    "FortiWeb":   ["FORTIWAFSID"],
}

WAF_ERROR_FINGERPRINTS: dict[str, list[str]] = {
    "Cloudflare":  ["Sorry, you have been blocked", "Ray ID:", "Attention Required! | Cloudflare", "cf-error-type"],
    "Akamai":      ["Reference #", "Your support ID is", "Access Denied", "akamaierror"],
    "Imperva":     ["Incapsula incident ID", "Request unsuccessful"],
    "AWS WAF":     ["Request blocked", "x-amzn-RequestId"],
    "F5 BIG-IP":   ["The requested URL was rejected", "F5 Networks"],
    "Sucuri":      ["Access Denied - Sucuri Website Firewall"],
    "Barracuda":   ["barracuda networks", "You have been blocked"],
    "FortiWeb":    ["FortiWeb Application Firewall"],
    "Wordfence":   ["generated by Wordfence", "This site is protected by Wordfence"],
    "ModSecurity": ["Not Acceptable!", "mod_security", "NAXSI"],
}

WAF_JS_CHALLENGES: dict[str, list[str]] = {
    "Cloudflare": ["window._cf_chl_opt", "jschl_vc", "_cf_chl_prog", "__cf_chl_tk"],
    "Imperva":    ["incapsula", "_Incapsula_Resource"],
    "Akamai":     ["_abck", "bm_sz", "ak_bmsc"],
    "StackPath":  ["StackPath"],
    "DataDome":   ["datadome", "dd_ru"],
    "PerimeterX": ["_pxhd", "_pxde", "pxCaptcha"],
    "Shape":      ["fncls.ssp"],
}

MALICIOUS_PROBE = "' OR 1=1-- <script>alert(1)</script> ../../../etc/passwd"


async def _check_js_challenge(html: str) -> str | None:
    for waf, patterns in WAF_JS_CHALLENGES.items():
        for pattern in patterns:
            if pattern.lower() in html.lower():
                return waf
    return None


async def run(
    target: str,
    session: Any = None,
    scope: Any = None,
    rate_limiter: Any = None,
    proxy: str | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    url = target if "://" in target else f"https://{target}"
    console.print(f"\n[module] WAF Detection[/module] → [target]{url}[/target]")

    detected: str | None = None
    confidence: int = 0
    evidence: list[str] = []

    async with TalismanHTTPClient(proxy=proxy, timeout=15) as client:
        # — Layer 1: Clean request — headers & cookies ——————————————
        try:
            r = await client.get(url)
            headers = {k.lower(): v.lower() for k, v in r.headers.items()}
            cookies = [c.name for c in r.cookies]
            html = r.text

            for waf, sigs in WAF_HEADER_SIGNATURES.items():
                for hk, pattern in sigs:
                    if hk in headers:
                        if pattern is None or re.search(pattern, headers[hk], re.IGNORECASE):
                            detected = waf
                            confidence += 40
                            evidence.append(f"Header: {hk}")
                            break

            for waf, cookie_patterns in WAF_COOKIE_SIGNATURES.items():
                for cp in cookie_patterns:
                    if any(c.startswith(cp) or cp in c for c in cookies):
                        if detected is None:
                            detected = waf
                        confidence += 30
                        evidence.append(f"Cookie: {cp}")

            # Layer 1b: JS challenge
            js_waf = await _check_js_challenge(html)
            if js_waf:
                detected = js_waf
                confidence += 50
                evidence.append("JS challenge detected")

        except Exception as e:
            log.debug("waf_detect_layer1", error=str(e))

        # — Layer 2: Malicious probe — error page fingerprint ————————
        try:
            probe_url = url + f"/?test={MALICIOUS_PROBE}"
            r2 = await client.get(probe_url)
            error_html = r2.text

            if r2.status_code in (403, 406, 429, 503):
                confidence += 20
                evidence.append(f"Blocked status: {r2.status_code}")

            for waf, patterns in WAF_ERROR_FINGERPRINTS.items():
                for pattern in patterns:
                    if pattern.lower() in error_html.lower():
                        if detected is None:
                            detected = waf
                        confidence = min(100, confidence + 35)
                        evidence.append(f"Error page: {pattern[:40]}")
                        break

        except Exception as e:
            log.debug("waf_detect_layer2", error=str(e))

    confidence = min(100, confidence)
    if detected:
        console.print(f"  [warning] WAF detected: {detected} (confidence: {confidence}%)[/warning]")
        console.print(f"  Evidence: {', '.join(evidence)}")
    else:
        console.print("  [green]No WAF detected[/green]")

    if session:
        await session.add_target(url, waf_detected=detected)

    return {
        "target": url,
        "waf": detected,
        "confidence": confidence,
        "evidence": evidence,
    }
