"""Technology fingerprinting — headers, cookies, HTML patterns, favicon hashing."""
from __future__ import annotations
import hashlib
import json
import re
from typing import Any
import mmh3
from talisman.utils.http_client import TalismanHTTPClient
from talisman.utils.logger import get_logger, console

log = get_logger(__name__)

TECH_SIGNATURES: dict[str, dict[str, Any]] = {
    "WordPress":       {"headers": {"x-powered-by": r"WordPress"}, "html": r"wp-content|wp-includes|/wp-json/", "cookies": ["wordpress_", "wp-settings"]},
    "Joomla":          {"html": r"Joomla|/media/jui/|option=com_"},
    "Drupal":          {"headers": {"x-generator": r"Drupal"}, "html": r"Drupal\.settings|/sites/default/", "cookies": ["SESS", "SESSdrupal"]},
    "Magento":         {"html": r"Mage\.|/skin/frontend/|Magento"},
    "Shopify":         {"html": r"Shopify\.theme|cdn\.shopify\.com"},
    "WooCommerce":     {"html": r"woocommerce|WC_|is-checkout"},
    "Laravel":         {"cookies": ["laravel_session", "XSRF-TOKEN"], "headers": {"x-powered-by": r"PHP"}},
    "Django":          {"cookies": ["csrftoken", "sessionid"], "headers": {"x-frame-options": r"SAMEORIGIN"}},
    "Ruby on Rails":   {"headers": {"x-powered-by": r"Phusion Passenger"}, "html": r"csrf-token|authenticity_token"},
    "Spring Boot":     {"headers": {"x-application-context": r"."}, "html": r"Whitelabel Error Page|Spring Framework"},
    "ASP.NET":         {"cookies": ["ASP.NET_SessionId", ".ASPXAUTH"], "headers": {"x-aspnet-version": r".", "x-aspnetmvc-version": r"."}},
    "Express":         {"headers": {"x-powered-by": r"Express"}},
    "Next.js":         {"headers": {"x-powered-by": r"Next\.js"}, "html": r"__NEXT_DATA__"},
    "Nuxt.js":         {"html": r"__NUXT__|nuxt-link"},
    "React":           {"html": r"__reactFiber|react-dom|reactjs"},
    "Angular":         {"html": r"ng-version|ng-app|angular\.min\.js"},
    "Vue.js":          {"html": r"Vue\.version|v-bind:|@click="},
    "nginx":           {"headers": {"server": r"nginx"}},
    "Apache":          {"headers": {"server": r"Apache"}},
    "IIS":             {"headers": {"server": r"IIS", "x-powered-by": r"ASP\.NET"}},
    "Cloudflare":      {"headers": {"server": r"cloudflare", "cf-ray": r"."}},
    "Akamai":          {"headers": {"server": r"AkamaiGHost", "x-akamai-transformed": r"."}},
    "AWS CloudFront":  {"headers": {"via": r"CloudFront", "x-amz-cf-id": r"."}},
    "PHP":             {"headers": {"x-powered-by": r"PHP/"}, "html": r"\.php"},
    "Java":            {"headers": {"x-powered-by": r"Servlet|JSP|Tomcat"}, "cookies": ["JSESSIONID"]},
    "Node.js":         {"headers": {"x-powered-by": r"Node\.js"}},
    "Python":          {"headers": {"x-powered-by": r"Python|Django|Flask|Gunicorn"}},
    "jQuery":          {"html": r"jquery\.min\.js|jQuery v"},
    "Bootstrap":       {"html": r"bootstrap\.min\.(css|js)|Bootstrap"},
    "Varnish":         {"headers": {"via": r"varnish", "x-varnish": r"."}},
    "Tomcat":          {"headers": {"server": r"Apache-Coyote|Tomcat"}},
    "Jenkins":         {"html": r"Jenkins|hudson\.model"},
    "GitLab":          {"html": r"GitLab|gl-button"},
    "Grafana":         {"html": r"Grafana|grafana\."},
    "Kibana":          {"html": r"Kibana|kibana-app"},
    "Elasticsearch":   {"html": r'"cluster_name"'},
    "Swagger UI":      {"html": r"swagger-ui|SwaggerUIBundle|swagger\.json"},
    "GraphQL":         {"html": r"__schema|GraphiQL|graphql"},
}

WAF_SIGNATURES: dict[str, dict[str, Any]] = {
    "Cloudflare":      {"headers": {"server": r"cloudflare"}, "error_html": r"Attention Required.*Cloudflare|Ray ID:"},
    "Akamai":          {"headers": {"server": r"AkamaiGHost"}, "error_html": r"Reference #|Access Denied.*Akamai"},
    "AWS WAF":         {"headers": {"x-amzn-requestid": r"."}, "error_html": r"Request blocked"},
    "Imperva":         {"headers": {"x-iinfo": r"."}, "cookies": ["incap_ses_", "visid_incap_"], "error_html": r"Incapsula incident"},
    "F5 BIG-IP":       {"headers": {"server": r"BigIP"}, "cookies": ["BIGipServer"], "error_html": r"The requested URL was rejected"},
    "Barracuda":       {"cookies": ["barra_counter_session="], "error_html": r"barracuda networks"},
    "Sucuri":          {"headers": {"x-sucuri-id": r"."}, "error_html": r"Sucuri Website Firewall"},
    "ModSecurity":     {"headers": {"server": r"Mod_Security"}, "error_html": r"mod_security|NAXSI"},
    "FortiWeb":        {"cookies": ["FORTIWAFSID="], "error_html": r"FortiWeb Application Firewall"},
    "Wordfence":       {"error_html": r"Wordfence|wordfence|generated by Wordfence"},
    "Azure Front Door":{"headers": {"x-azure-ref": r"."}},
}

async def _get_favicon_hash(url: str, client: TalismanHTTPClient) -> str | None:
    try:
        for path in ["/favicon.ico", "/favicon.png"]:
            r = await client.get(url.rstrip("/") + path)
            if r.status_code == 200 and r.content:
                return str(mmh3.hash(r.content))
    except Exception:
        pass
    return None

async def run(
    target: str,
    session: Any = None,
    scope: Any = None,
    rate_limiter: Any = None,
    proxy: str | None = None,
    waf_detect: bool = True,
    favicon_hash: bool = True,
    **kwargs: Any,
) -> dict[str, Any]:
    url = target if "://" in target else f"https://{target}"
    console.print(f"\n[module] Technology Detection[/module] → [target]{url}[/target]")
    detected_tech: list[str] = []
    detected_waf: str | None = None
    favicon: str | None = None
    async with TalismanHTTPClient(proxy=proxy, timeout=15) as client:
        try:
            r = await client.get(url)
            headers = {k.lower(): v for k, v in r.headers.items()}
            html = r.text[:50000]
            cookies = [c.name for c in r.cookies]
            for tech, sigs in TECH_SIGNATURES.items():
                matched = False
                if "headers" in sigs:
                    for hk, pattern in sigs["headers"].items():
                        if hk in headers and re.search(pattern, headers[hk], re.IGNORECASE):
                            matched = True
                            break
                if not matched and "html" in sigs:
                    if re.search(sigs["html"], html, re.IGNORECASE):
                        matched = True
                if not matched and "cookies" in sigs:
                    if any(ck for ck in cookies if any(ck.startswith(c) for c in sigs["cookies"])):
                        matched = True
                if matched:
                    detected_tech.append(tech)
            if waf_detect:
                for waf, sigs in WAF_SIGNATURES.items():
                    w_matched = False
                    if "headers" in sigs:
                        for hk, pattern in sigs["headers"].items():
                            if hk in headers and re.search(pattern, headers[hk], re.IGNORECASE):
                                w_matched = True
                                break
                    if not w_matched and "cookies" in sigs:
                        if any(ck for ck in cookies if any(ck.startswith(c) for c in sigs.get("cookies", []))):
                            w_matched = True
                    if not w_matched and "error_html" in sigs:
                        try:
                            probe = await client.get(url + "/?<script>", timeout=10)
                            if re.search(sigs["error_html"], probe.text, re.IGNORECASE):
                                w_matched = True
                        except Exception:
                            pass
                    if w_matched:
                        detected_waf = waf
                        break
            if favicon_hash:
                favicon = await _get_favicon_hash(url, client)
        except Exception as e:
            log.warning("tech_detect_error", url=url, error=str(e))
    if detected_tech:
        console.print(f"  Tech: {', '.join(detected_tech)}")
    if detected_waf:
        console.print(f"  [warning] WAF detected: {detected_waf}[/warning]")
    if favicon:
        console.print(f"  Favicon hash: {favicon}")
    if session:
        for t in url, target:
            if scope and scope.is_in_scope(t):
                await session.add_target(url, tech_stack=detected_tech, waf_detected=detected_waf)
    return {
        "target": url,
        "technologies": detected_tech,
        "waf": detected_waf,
        "favicon_hash": favicon,
    }
